### ISSUE TITLE
BASK1: Initialize the Project with Spring Initializr

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#1]
# **User Story**

## What Needs To Be Done
- As a customer, I need the actual project to be created. 

## Acceptance Criteria
- Project is created
- Maven (clean install works) 
- Has required dependencies
- Has Application.java (Main Class)
- Main class runs properly

## Technical Information
- Initial Dependencies Needed
   - Spring Web
   - Spring JPA
   - Spring DevTools
   - H2
   - Vaadin
   - JUnit
   - Mockito

**Comment by Clearedkinkajou** [comment]
QA Passed
