### ISSUE TITLE
BASK42: Unit Tests for Following a User

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#102]
# Testing
# What Needs to be Tested
* Need to test following a user and unfollowing a user works correctly

# Acceptance Criteria
* Following a User works
* Unfollowing a User works

# Technical Information
* In the ProfileTests class
* Using the ProfilePresenter methods create the 2 unit tests

**Comment by mteolis** [comment]
no QA required: unit tests
