### ISSUE TITLE
BASK43: Unit Tests for Posting a Tweet

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#103]
# Testing
# What Needs to be Tested
* Need to test posting a tweet and posting an empty tweet

# Acceptance Criteria
* Posting a tweet works
* Posting an empty tweet doesnt work

# Technical Information
* In the TweetTests class
* Using the TweetPresenter methods create the 2 unit tests

**Comment by Clearedkinkajou** [comment]
No QA Needed (Unit Test Ticket)
