### ISSUE TITLE
BASK45: Unit Tests for CRUD for Tweet

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#105]
# Testing
# What Needs to be Tested
* Need to test if all crud operations work on the user tweet

# Acceptance Criteria
* Create a Tweet works
* Retrieve a Tweet works
* Delete a Tweet works
* Update a Tweet works

# Technical Information
* Using the CrudTests class from #104 
* Create 4 unit tests for each operation

**Comment by mteolis** [comment]
no QA required: unit tests
