### ISSUE TITLE
BASK47: Decorating the TweetDisplayComponent/CommentDisplayComponent 

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#111]
# USER STORY
## What Needs To Be Done
- As a customer, I want to see nice tweets and nice comments 

## Acceptance Criteria
- The tweet looks proper and displayed nicely
- The comments look proper and displayed nicely

## Technical Information
- Use CSS and VaadinCSS

**Comment by cristian-aldea** [comment]
Acceptance Testing for User Story BASK47:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Looked at the display components for tweets and comments | Expected a significantly more informative and appealing user interface | Just as expected |
| Clicked on the username of a tweet/comment | Redirected to the corresponding user's profile | Just as expected |

All acceptance tests passed.
