### ISSUE TITLE
BASK48: Hiding/Unhiding Comments

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#112]
# USER STORY
## What Needs To Be Done
- As a customer, I want to be able to hide and unhide the comments on a Tweet

## Acceptance Criteria
- You can hide/unhide comments
- There is a clear button on how to do this

## Technical Information
- Use the TweetDisplayComponent to implement this

**Comment by Pwnagebird** [comment]
QA Failed:
  - Comment button changes depending on which screen it is on. Needs to be the same on every screen

CC: @Clearedkinkajou 


@CaoGreg  and @cvu1998  Please fix and do another pull request

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK48:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| I navigate on the home page and see a tweet with many comments | All the comments are initially hidden | Just as expected |
| I click the "show comments" button | The first 5 comments are shown | Just as expected |
| I click the "hide comments" button | All comments are hidden | Just as expected |
| I click the "show comments" button until all comments are shown | All comments are shown | Just as expected |
| I click the "hide comments" button | All comments are hidden | Just as expected |


All acceptance tests passed.
