### ISSUE TITLE
BASK49: Deleting Tweets 

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#113]
# USER STORY
## What Needs To Be Done
- As a customer, I want to be able to delete my own tweets. 

## Acceptance Criteria
- You can delete tweets
- Clear delete button
- Deletes tweet from DB

## Technical Information
- Use the TweetDisplayComponent to implement this

**Comment by Pwnagebird** [comment]
@TheGreatMarkus  Can you please QA this when you get a chance! Thanks

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK49:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Signed up as a new user | New account would be created and I would be redirected to the home page | Just as expected |
| Created a new tweet | Tweet would show up on my profile with a "Delete" button | Just as expected |
| pressed the "Delete" button | tweet should be removed from my profile page, home page and from the db | Just as expected |

All acceptance tests passed.
