### ISSUE TITLE
BASK50: Unit Tests for Retweeting a Tweet 

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#114]
# Testing
# What Needs to be Tested
* Need to test if retweeting a tweet works
# Acceptance Criteria
* Retweet Tweet works
* The new Tweet exists in the database
* The reTweet is paired with the user that reTweeted

# Technical Information
* Using the Tweet Presenter

**Comment by Clearedkinkajou** [comment]
# Testing
# What Needs to be Tested
* Need to test if retweeting a tweet works
# Acceptance Criteria
* Retweet Tweet works
* The new Tweet exists in the database
* The reTweet is paired with the user that reTweeted

# Technical Information
* Using the Tweet Presenter

**Comment by Pwnagebird** [comment]
No QA Required (Unit Tests)
