### ISSUE TITLE
BASK51: Unit Tests for Commenting on a Tweet

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#115]
# Testing
# What Needs to be Tested
* Need to test if commenting on a tweet works
# Acceptance Criteria
* Check if You can post a comment
* Check if you can't post an empty comment

# Technical Information
* Using the Tweet Presenter

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK51: No QA Necessary for Unit Test Issues
