### ISSUE TITLE
BASK9: Initializing Tweet Object, Tweet Service and Tweet Repository

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#12]
### What Needs To Be Done
* As a developer, we need to be able to have a set of tweets that we can add to a feed

### Acceptance Criteria
* Tweet Object
* Tweet Service 
* Tweet Repository

### Technical Information
* You must have @Id and @GenerateValue(stategy= GenerationType.table) in the tweets object id 
* Tweet service must be annotated with @Service
* Tweet class must be annotated with @Entity
* Tweet service should have no methods
* Tweet class should have the following fields
   * ID
   * Text (string)
   * Likes (ints)
   * Retweets (ints)
   * User 
* Tweet repository should have the following methods
  * find tweet list from user

**Comment by Pwnagebird** [comment]
QA PASSED:
  - Program runs!
