### ISSUE TITLE
BASK56: Trimming the Inputs for Tweets and Comments

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#120]
# TASK
## What Needs To Be Done
- The tweets, comments and bio need to not have unnecessary white-space and shouldn't be too long

## Acceptance Criteria
- Can't have any whitespace at the start/end of a tweet, comment, or bio.
- Can't have more than 2 newlines in a row within a tweet, comment, or bio.
- Restrict the tweet character limit to 250 characters  

## Technical Information
- trim inputs, similar to the trim() method in PHP
- remove extra newlines when there are more than two in a row.
- Restrict the number of allowed characters to 250.

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK56:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| I create a tweet with whitespace at the beginning/end and with many newlines between different lines of text | The edge whitespace should be removed and there should only be at most two newlines in succession | Just as expected |
| I create a comment with unnecessary whitespace | the comment text should be cleaned in the same manner as the tweet | Just as expected |
| I edit my bio with unnecessary whitespace | the bio text should be cleaned in the same manner as the tweet or comment | Just as expected |
| I try typing more than 250 characters in my tweet | the text area should prevent me from writing additional characters | Just as expected |

Before:
![image](https://user-images.githubusercontent.com/23544999/54883912-1ee9f280-4e41-11e9-866f-9381b02755e6.png)


After:
![image](https://user-images.githubusercontent.com/23544999/54883913-25786a00-4e41-11e9-9b3b-4c414618dcfe.png)


I cannot enter any more character past this point:
![image](https://user-images.githubusercontent.com/23544999/54883866-b733a780-4e40-11e9-876c-6c33ede97c89.png)


All acceptance tests passed.
