### ISSUE TITLE
BASK57: Usernames should not be allowed to have spaces

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#121]
# TASK
## What Needs To Be Done
- When creating an account, or logging in,, you should not be allowed to have spaces in your username

## Acceptance Criteria
- No spaces in username 

## Technical Information
- Don't allow uses to press SPACE in the username textbox

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK57:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Ran program | Server started without issues | Same as expected |
| Tried typing any white space characters (space, \n, \t, etc.)  | The input is ignored | Same as expected |
| Tried typing any non-white space characters (numbers, letters, symbols, etc)  | The input is accepted | Same as expected |

All acceptance tests passed.
