### ISSUE TITLE
BASK58: Securing Passwords 

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#122]
# USER STORY
## What Needs To Be Done
- As a customer, I want my password to be secure 

## Acceptance Criteria
- After signup, the password has some sort of secure algorithm to hide the actual password and then saved in the DB
- When logging in, it should use the algorithm to get the password from the DB

## Technical Information
- Can use Hashing/Salt/Encryption

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK58:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Create a new account  | The raw password shouldn't show up anywhere in the database | Just as expected |
| Login with correct password  | Despite the plain password not being stored in the db, the login should still succeed if the same password is used | Just as expected |
| Login with new account  | The user can't login if the wrong password is used | Just as expected |

![image](https://user-images.githubusercontent.com/23544999/54883637-0d531b80-4e3e-11e9-9693-40245ceada45.png)

All acceptance tests passed.
