### ISSUE TITLE
BASK59: Fixing the Vaadin Logout Bug

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#131]
# BUG
## How to Reproduce
* Log in to any user, and then log out, and you will see a bunch of vaadin errors on the top right of your screen

## Expected Outcome
* Sucessful log out and no vaadin errors

## Actual Outcome
* A bunch of vaadin popups show up

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK59:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Ran Program | Server starts without issues | Same as Expected |
| Logged in as Markus | Redirected to the home view | Same as Expected |
| Logged out | No Vaadin error messages appear | Same as Expected |


All acceptance tests passed.
