### ISSUE TITLE
BASK60: Finishing up the decoration of all pages

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#132]
# USER STORY
## What Needs To Be Done
- As a customer, I want all my pages to look nice and pleasing to the eye

## Acceptance Criteria
- All pages have the same font
- All pages use the same color scheme
- Pages look nice
- Everything is spaced properly 

## Technical Information
- Use CSS and VaadinCSS

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK60:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Looked around the user interface (login, home, profile) | Expected a significantly more appealing user interface and consistent fonts and colour usage across pages | Just as expected |

All acceptance tests passed.
