### ISSUE TITLE
BASK61: Going to localhost:8080/profile while not logged in bug

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#133]
# Bug

## How to reproduce
* While not logged in, and you go to localhost:8080/profile you get an error page 

## Actual Outcome
* You get an error page

## Expected Outcome
* Should be redirected back to the login page correctly

**Comment by TheGreatMarkus** [comment]
These changes were reverted by commit 1b60bb85a40bf06ee0f18f1e048fcc1cf7467e0b and will be hotfixed in

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK61:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Started program | Server runs without issues | Same as expected |
| Navigated to "http://localhost:8080/profile" without first logging in | I am redirected to "http://localhost:8080/", which is the login page | Same as expected |
| Navigated to "http://localhost:8080/profile/username" (for any username) without first logging in | I am redirected to "http://localhost:8080/", which is the login page | Same as expected |

All acceptance tests passed.
