### ISSUE TITLE
BASK11: CRUD for User Service

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#14]
### What Needs To Be Done

* As a developer, we need to Create, Remove, Update, and Delete User objects in our database

### Acceptance Criteria
* Create Method in User service
* Update Method in User  service
* Remove Method in User  service
* Delete Method in User  service
* Unit tests for each method
* Autowire the repository into the service class

### Technical Information
* Create UserTests.java
* WONT DO: Use JUnit to tests methods

**Comment by Pwnagebird** [comment]
As discussed with @CaoGreg and @TheGreatMarkus, We will not implement the Unit tests but create a ticket for Integration tests to test #15 #16 and this ticket 

@Clearedkinkajou

**Comment by Pwnagebird** [comment]
QA PASSED:
    All operations worked, tested with script in Database wiki https://github.com/Pwnagebird/Basilisk/wiki/Database
