### ISSUE TITLE
BASK13: CRUD for Friends List Service

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#16]
### What Needs To Be Done

* As a developer, we need to Create, Remove, Update, and Delete Friends List objects in our database

### Acceptance Criteria
* Create Method in Friends List Service
* Update Method in Friends List Service
* Remove Method in Friends List Service
* Delete Method in Friends List Service
* Unit tests for each method
* Autowire the repository into the service class

### Technical Information
* Create FriendsListTest.java
* WONT DO: Use JUnit to tests methods

**Comment by Pwnagebird** [comment]
QA PASSED:
    All operations worked, tested with script in Database wiki https://github.com/Pwnagebird/Basilisk/wiki/Database
