### ISSUE TITLE
BASK15: Create Home Presenter

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#18]
### What Needs To Be Done

* As a developer, we need a way to communicate with our back end and front end. 

### Acceptance Criteria
* Create HomePresenter Class 
* Autowire Tweet Service
* Autowire User Service

### Technical Information
* @Autowired on the constructor

**Comment by Pwnagebird** [comment]
As discussed with @CaoGreg  and I, we added to our dependencies the log4j framework. Just add an attribute with this. You can see an example on #19 (profile presenter class)

**Comment by Clearedkinkajou** [comment]
QA Passed
* The existence of Home Presenter works as intended
