### ISSUE TITLE
BASK17: Being able to Login

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#20]
### What Needs To Be Done

* As a customer, I want to be able to login with my account

### Acceptance Criteria
* Being able to login 
* Only logging in if you have the correct username and password
* Wrong Password if password doesn't exist or account doesn't exist
* It should redirect you to home page of the correct user 

### Technical Information
* Hard code an account in the DB for this (think it can be done in application class) 
* How do we make it go to the users home page?
* Query Parameters?

### Tasks 

- [x] Implement listener on login button 

- [x] Implement Login

- [x] Implement Sessions

**Comment by Pwnagebird** [comment]
@TheGreatMarkus  and @mteolis . I think we should definitely do some research on how we can switch pages, sessions , cookies and everything in spring before we can really start this ticket. I really think we will run into errors  if we go into this ticket blind

CC:  @Clearedkinkajou

**Comment by Pwnagebird** [comment]
As discussed, moving this ticket to sprint 2, school is too hard for the next 3 days. We will tackle it in sprint 2
CC: @Clearedkinkajou  @najimgh  @TheGreatMarkus @mteolis

**Comment by Pwnagebird** [comment]
@mteolis @najimgh  @TheGreatMarkus  As we discussed, we need to do a lot of research on this so we can do this right the first time. We need to mix vaadin and spring together to make this work. We need to fix up the front end so the Login text boxes and button are isolated and have a listener. We need to figure out how the login works and how the sessions will work. We need a clear picture of what is going on. 

Please comment your design decisions as they're made and please work together on this ticket

CC: @Clearedkinkajou

**Comment by Clearedkinkajou** [comment]
@mteolis @najimgh @TheGreatMarkus Use current version of the develop branch and make a prototype of session. Doesn't matter how messy it is just get it working. In the prototype you have full access to go anywhere in the project. Just get sessions working. Once complete we will figure out how the prototype is to be refactored into BASK 17 and use the knowledge to understand how we need to create views and presenters to work with Spring security.

CC: @Pwnagebird

**Comment by TheGreatMarkus** [comment]
Implemented login with the help of @Pwnagebird @mteolis. Tested it with correct and wrong username/password. Waiting on @najimgh for the front end implementation.

**Comment by Pwnagebird** [comment]
As discussed, we will need to create ticket for hashing the password 

CC: @mteolis @Clearedkinkajou  @TheGreatMarkus

**Comment by TheGreatMarkus** [comment]
Tests Performed (Sessions):
- Tried going to the home page, got redirected to the login page.
- Tried going to the profile page, got redirected to the login page.

- Logged in, got redirected to the home page. Could go to the profile page.
- Tried going back to the login page, was redirected to the home page.
- Refreshed page, session was still active.
- Closed/reopened tab, session was still active.
- Closed/reopened browser, session ended and was redirected to the login page.

- Created a session on one tab and was redirected automatically on another tab.

- Logged in on one browser but wasn't automatically logged into other browsers.

QA Passed for me. Did I miss anything @Pwnagebird @Clearedkinkajou ?

**Comment by TheGreatMarkus** [comment]
QA Passed
