### ISSUE TITLE
BASK18: JPA Object Persistence Bug

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#26]
# BUG

## The Problem
The program is currently not able to run because of the way the Entity classes of User, Tweet, and FriendList were create. The objects in their fields are not persisted correctly

## How to Reproduce
1) Run the program
2) See error message with JPA Persistance

## Technical Notes
* Need to add @Column to every field that is not an object
* Generate Getters and Setters for each field excluding ID
* Need to add @OnetoOne(cascade = CascadeType.ALL, targetEntity = User.class) and @JoinColumn(name="NAME") to the object fields

**Comment by TheGreatMarkus** [comment]
QA Passed, ran and built the project and no errors popped up.
