### ISSUE TITLE
BASK3: Configuring The Test Environment 

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#3]
# **User Story**

## What Needs To Be Done
- As a customer, I need to know my developers are running tests on the application

## Acceptance Criteria
- ApplicationTest.java class is created
- Unit Test for the application running works 

## Technical Information
- Use JUNIT and Mockito to design the test class

**Comment by Clearedkinkajou** [comment]
**QA Passed**
* Ran the new unit test and it passed
