### ISSUE TITLE
BASK20: Liking a Tweet

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#39]
# USER STORY
## What Needs To Be Done
As a customer, I would like to be able to like a tweet

## Acceptance Criteria
* Being able to like and unlike a tweet. 
* Some sort of indication it is liked already or not liked already
* PO ACCEPTANCE REQUIRED

## Technical Information
* Likes++
* Need a front end tweet component to hold the tweet object

**Comment by Pwnagebird** [comment]
Assigning this to me for now, when sprint planning #2 comes around we will dedicate it to developers. I am PO for this ticket
CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
One of our extra requirements are to dislike a tweet so I think we should just add it to this ticket since it is so similar
CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
@Clearedkinkajou  @TheGreatMarkus  As discussed, we completed the requirement of disliking a tweet as well in this ticket due to the similarity it had.

**Comment by Pwnagebird** [comment]
Likes and Dislikes are not simple integers anymore, we chose them to be lists so we could tell which users have liked the tweet

CC: @Clearedkinkajou

**Comment by cristian-aldea** [comment]
Acceptance Testing for User Story BASK20:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Logged in as Markus | Redirected to the home page | Just as expected |
| Clicked on Profile Page button | Redirected to the profile page | Just as expected |
| Compare profile page content with database | The tweets shown on the profile page should match the tweets in the database created by user Markus | Just as expected |
| Liked a tweet | The like should appear on the tweet component and the db. | Just as expected |
| Un-liked a tweet | The like should disappear from the tweet component and the db. | Just as expected |
| Disliked a tweet | The dislike should appear on the tweet component and the db. | Just as expected |
| Un-disliked a tweet | The dislike should disappear from the tweet component and the db. | Just as expected |
| Like a disliked tweet  | For the tweet, the dislike should disappear and a like should appear | Just as expected |
| Dislike a liked tweet  | For the tweet, the like should disappear and a dislike should appear | Just as expected |

All acceptance tests passed.
