### ISSUE TITLE
BASK21: Displaying Tweets and Creating a Tweet 

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#40]
# USER STORY
## What Needs To Be Done
As a customer, I would like to be able to post tweets to my profile

## Acceptance Criteria
* Being able to post a tweet and it appearing on the Users feed on their profile
* PO ACCEPTANCE REQUIRED

## Technical Information
* Should use the User Object from #11 

## Sub User Stories

#60 #61 #62

**Comment by Pwnagebird** [comment]
Assigning this to me for now, when sprint planning #2 comes around we will dedicate it to developers. I am PO for this ticket
CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
Will add to this ticket on Sprint 2 project planning

**Comment by Pwnagebird** [comment]
My mistake, We will add  more requirements during Sprint 2 project planning

CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
We do have an extra requirement to add comments to the tweets, lets try to keep that away from this ticket but keep in mind that this is something that will be required at a later date so we don't block it.

CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
This is technically blocked by #20 because we need a session user to create tweets.  This is a big ticket,  we need to focus and research how to properly do this with sessions

cc: @Clearedkinkajou

**Comment by Clearedkinkajou** [comment]
* Add dislike to tweet model
* Add TweetDisplayPresenter

**Comment by cristian-aldea** [comment]
Acceptance Testing for User Story BASK21:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Logged in as admin | Redirected to home page | Just as Expected |
| Clicked on profile page button | Redirected to profile page | Just as Expected |
| Wrote a tweet and clicked "Create" | Tweet shows up on the profile page and in the db | Just as Expected |
| Wrote an empty tweet and clicked "Create" | Tweet isn't published | Just as Expected |
| Exited Session and created a new session | Created tweets still shows up | Just as Expected |
| Logged in as another user | Tweets created as admin didn't show up on my profile page | Just as Expected |


All acceptance tests passed.
