### ISSUE TITLE
BASK25: Decorating the Profile Page

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#49]
# USER STORY
## What Needs To Be Done
As a customer, I would like to see a nice profile page when going to my profile

## Acceptance Criteria
* Profile must look nice and presentable for the user

## Technical Information
* CSS It Up!
* Please limit the biography to 280 characters

**Comment by Pwnagebird** [comment]
Assigning this to me for now until Sprint Planning for sprint 2 and will fill more requirements out during project planning

CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
As discussed taking this out of Sprint #2 

CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
If you put a biography way too long, and then create a tweet, itll crash the page on loading. Need to limit the characters. 

@TheGreatMarkus  if you have time can you look into this

CC: @Clearedkinkajou

**Comment by TheGreatMarkus** [comment]
How long does the comment need to be? @Pwnagebird

**Comment by Pwnagebird** [comment]
QA PASSED
   - Looks good!
