### ISSUE TITLE
BASK26: Decorating the Home Page

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#50]
USER STORY
What Needs To Be Done
As a customer, I would like to see a nice home page so I can view my feed

Acceptance Criteria
* Make the home page follow the design and colors of the profile page.

Technical Information
* CSS It Up!

**Comment by Pwnagebird** [comment]
Assigning this to me for now until we have plan it into a sprint

CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
There seems to be no validations on this page since the components will have their own validations. Changing the ticket scope to just designing the home page

CC: @Clearedkinkajou  @TheGreatMarkus

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK26:

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Logged in as Markus and went to the home page | The page clearly display important information such as tweets, likes and dislikes, comments, etc. | Same as Expected |

All acceptance tests passed.
