### ISSUE TITLE
BASK27: Retweet a Tweet

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#51]
# USER STORY
## What Needs To Be Done
As a customer, I would like to be able to retweet a tweet 

## Acceptance Criteria
When a user retweets a tweet, it should show up in their feed. In terms of order, a recent retweet should show up near the top of the feed for a user, regardless of when the tweet was made.

## Technical Information
- A Retweet model will need to be created (along with the retweet repo and service).
- A Retweets field will need to be added to the user, with a one-to-many relation between user and retweet.

**Comment by Pwnagebird** [comment]
Assigning this to me for now until we have plan it into a sprint

CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
If someone retweets a tweet, should it be at the top of their feed on their own profile?

@Clearedkinkajou  @TheGreatMarkus

**Comment by TheGreatMarkus** [comment]
@Pwnagebird @Clearedkinkajou We decided that we will create a new Model that is called Retweet. This model will have three fields:
- User: The user that retweeted
- Tweet: The retweeted tweet
- Timestamp: The time that the retweet was done.

The user will then have a new field: Retweets. This will be a list of Retweets. The relation between User and Retweet will be One-to-Many

**Comment by TheGreatMarkus** [comment]
Acceptance Testing for User Story BASK27

| Action | Expected Result | Actual Result |
| --- | --- | --- |
| Logged in as Markus | Redirected to the home page | Just as expected |
| Looked at the feed of tweets on the home page | The tweet would be ordered from newest to oldest | After double-checking with the database, just as expected. |
| Followed a user with tweets | Their tweets would appear on my home screen, sorted with the other tweets from my existing | Just as expected |
| Unfollowed another user | Their tweets would disappear from my feed | Just as expected |
| Retweeted a tweet as admin, to whom Markus is following | Markus should see the retweet as the first thing on his feed, regardless of the time stamp of the original tweet |
| Created a new tweet as Markus | This tweet should appear at the top of the feed | Just as expected |
| Retweeted a tweet as Markus | This Retweet should appear at the top of the feed | Just as expected |


Tests passed.
