### ISSUE TITLE
BASK28: Comment on a Tweet

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#52]
# USER STORY
What Needs To Be Done
As a customer, I would like to be able to comment on tweets

# Acceptance Criteria
* Can comment on a tweet
* Comment shows under the tweet

# Technical Information
* Add a new Model called Comment (with the associated repo and service)
* Need to use CommentDisplayComponent and CommentCreateComponent

**Comment by Pwnagebird** [comment]
Assigning this to me for now until we have plan it into a sprint

CC: @Clearedkinkajou

**Comment by Pwnagebird** [comment]
Should the comments be from newest to oldest or vice versa? @Clearedkinkajou  @TheGreatMarkus

**Comment by TheGreatMarkus** [comment]
QA Passed.

Details:
- Logged in as Markus.
- Commented on various tweets on my home page. These comments were displayed under the tweet. They persisted through reloading the server.
- Went to my profile page, commented on my tweets, these comments behaved correctly.
