### ISSUE TITLE
BASK29: Bio, Stats and Images on the Profile Page

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#53]
# USER STORY
## What Needs To Be Done
As a customer, I would like to be able to update my profile picture, edit my biography, and see my stats.

## Acceptance Criteria
* The user should be able to go to their profile page, change a detail (bio, profile picture), and these changes should show and persist after the change was done.
* Should be able to see the stats of people you're following, your followers and your retweets.

## Technical Information
The user will need to have new fields depending on what the profile page will contain:
* Bio
* Profile picture
* Stats Bar

**Comment by Pwnagebird** [comment]
Assigning this to me for now until we have plan it into a sprint

CC: @Clearedkinkajou

**Comment by TheGreatMarkus** [comment]
QA Passed.

Details:
- Logged in as Makus and went to the profile page.
- Saw that my bio was empty, I changed it.
- I refreshed the page, logged out and rebooted the server, the bio was still as I left it.
- Uploaded a profile and cover photo.
- Both photos persisted through refresh, logout and server restart.
