### ISSUE TITLE
BASK31: Refactor Login Page into a Complete UI

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#55]
# Task

## What needs to be done
We need to be able to have a view that has a strong foundation and has a modular design. Including the ability to communicate with the back-end and not have hard coded strings in the view

## Acceptance Criteria 
 * Uses HTML
 * Extends PolymerTemplate<>
 * Presenter is injected into view

## Technical Information
 * You need to extend polymertemplate because that's how Vaadin links the HTML, Java, and Javascript together
 * Component creation
 * Spring injection of presenter
 * Vaadin Tags

**Comment by TheGreatMarkus** [comment]
Test Performed (Login Page):
- Entered correct credentials, logged in.
- Entered wrong password, got an error message for the password.
- Entered wrong username, still got an error message for the password. The message was fine however.

Suggested Improvements:
- Pressing Enter should log you in when in the password field.
- The invalid credential message shouldn't be set to the password field. It should be set to something more general which includes both fields (some container maybe idk). Also, the username field should also be set as invalid.

Thoughts? @Clearedkinkajou @Clearedkinkajou @najimgh

**Comment by TheGreatMarkus** [comment]
QA Passed
However, we should write down these suggestions for later:
- Pressing Enter should log you in when in the password field.
- The invalid credential message shouldn't be set to the password field. It should be set to something more general which includes both fields (some container maybe idk). Also, the username field should also be set as invalid.
