### ISSUE TITLE
BASK32: Refactor Home Page into a Complete UI

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#56]
# Task

## What needs to be done
We need to be able to have a view that has a strong foundation and has a modular design. Including the ability to communicate with the back-end and not have hard coded strings in the view

## Acceptance Criteria 
 * Uses HTML
 * Extends PolymerTemplate<>
 * Presenter is injected into view

## Technical Information
 * You need to extend polymertemplate because that's how Vaadin links the HTML, Java, and Javascript together
 * Component creation
 * Spring injection of presenter
 * new Vaadin tags

**Comment by TheGreatMarkus** [comment]
QA Checks:

- After logging in, I am redirected to the home page and the page is loaded correctly
- The home view uses html in the home-view.html file.
- The home view extends PolymerTemplate
- The HomePresenter object is injected into the view.
- The page has no functionality as of now. This is expected.

Suggestions:
1. The Home and Profile tabs should be replaced with:
	- text indicating that the current page is the home page.
	- A button that, when pressed, redirects to the profile page.

QA Passed, but the suggestion given should be noted somewhere for future reference.

**Comment by TheGreatMarkus** [comment]
@Clearedkinkajou @cvu1998 @Pwnagebird Please have a look at my comment before closing the ticket.

**Comment by Pwnagebird** [comment]
Absolutely agree on both the suggests, tickets will be created @TheGreatMarkus
