### ISSUE TITLE
BASK33: Navigating Pages & Logging Out

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#69]
# USER STORY
## What Needs To Be Done
As a customer, I would like to be able to navigate between pages in my website. As well, I would like to be able to logout of my account.

## Acceptance Criteria
* Can logout
* Can navigate to home
* Can Navigate to profile

## Technical Information
* Using VaadinSession for Logging Out

**Comment by TheGreatMarkus** [comment]
QA passed. The application's behavior is acceptable.

Details:
- Logged in as Markus
- Naviguated from Home to Profile and back without any issues
- Clicked on the logout button from the home and profile pages, got redirected to the login page.
- Tried to go to /home and /profile and was redirected to the login page. The currentUser parameter was effectively nulled.
- The search bar has no functionality, as expected.
