### ISSUE TITLE
BASK34: Being Able to Create a New Account

### ISSUE THREAD

**Issue by Pwnagebird** [Pwnagebird/Basilisk#72]
# USER STORY
## What Needs To Be Done
As a customer, I would like to be able to register a new account

## Acceptance Criteria
* Registration part on login view (username, fullname, password signup button) 
* Account created in DB
* New account can login 
* Redirection to profile page 

## Technical Information
* Use the LoginPresenter, UserService and UserRepository 
* Textbox for full name, username, and password and sign up button called backend to create account

**Comment by TheGreatMarkus** [comment]
QA Passed.

Details:
- The login page has indeed a registration part to allow the user to create a new account
- I tried creating a new account with the usernames of a few existing accounts (ignoring case) and it failed as expected.
- I used a new username and was able to create a new account
- I was redirected immediately to my profile page when the account was created.
