### ISSUE TITLE
BASK35: Search & See Other User Profiles

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#73]
# USER STORY
## What Needs To Be Done
As a customer, I need to be able to find other users so that I can follow them.

## Acceptance Criteria
* Has Search Bar
* Can navigate to the person clicked
* Can follow a user

## Technical Information
"TO BE DISCUSSED DURING PROJECT PLANNING SPRINT 3"

**Comment by TheGreatMarkus** [comment]
QA Passed.

Details:
- Searched for a user, clicked on their name in the drop down list and was redirected to their profile page.
- I can't post tweets if I'm on somebody else's profile page. As expected.
- typing any string that corresponds to the part of a username redirects me to their profile page.
