### ISSUE TITLE
BASK35.2: Can Navigate to Other User Profiles

### ISSUE THREAD

**Issue by Clearedkinkajou** [Pwnagebird/Basilisk#75]
# SUB USER STORY TO #73
## What Needs To Be Done
As a customer, after having searched for a user, I want to be able to see their profile page.

## Acceptance Criteria
* The profile page of other users should be accessible through the UI, and include the basic info, stats and tweets of the other user.

## Technical Information
* Modify Profile View to be general to any user, not just the current user.

**Comment by TheGreatMarkus** [comment]
Added Details to the issue.
